### ISSUE TITLE
Bug: "Feels Like" Temp Wrong & Missing Provider Logo

### ISSUE THREAD

**Issue by mgonzales71** [powlo/weather.metoffice#3]
In testing various Kodi weather providers for a skin feature change I noticed the following with the Met Office Kodi weather provider:

"feels like" weather temp was obviously not right and the weather provider logo wasn't being displayed (missing).

![2015-04-26_14-36-41](https://cloud.githubusercontent.com/assets/6510026/7339411/68801756-ec22-11e4-9c44-eef8cbace823.jpg)

**Comment by mgonzales71** [comment]
Forgot to mention testing was done in the skin Titan (Helix):

https://github.com/marcelveldt/xbmc.skin.titan/tree/master/skin.titan.helix

**Comment by powlo** [comment]
What locations did you have set? There's forecast location, observation location and regional location.

And what are your System temperature units set to?

Not sure about weather provider logo. I'd need to investigate. My guess is that this is a new thing that isn't currently shipped with Met Office addon.

**Comment by mgonzales71** [comment]
see above screenshot - Heathrow was my test setting for location, etc.

all the other weather service addon's provide a logo - try for example yahoo or openweathermap

my system is set to use F for temp.

I had a Marcel (who is the author of the skin: Titan) test this provider as well - he lives in the Netherlands and uses C for his temp and he had the same issues.

**Comment by powlo** [comment]
Appologies for the delay, I've fixed the "Feels Like" issue. The Met Office doesn't provide this information, so a null value is set. (An unfortunate side-effect is that Kodi will try to fix this and set the value to 0 deg C.)

The latest release of Weather.MetOffice also includes a provider logo.
