### ISSUE TITLE
http error 403: Forbidden

### ISSUE THREAD

**Issue by scerazy** [powlo/weather.metoffice#4]
It does not work for few months now
Error comes from http://datapoint.metoffice.gov.uk/public/data/val/wxobs/all/json

**Comment by powlo** [comment]
Thanks, I'm working on an update.

**Comment by powlo** [comment]
There's a new version for Krypton. Can you check if you're still getting an error?

**Comment by ehuggett** [comment]
Version 2.0.0 installed from the kodi add-on repository works for me right now (never used it before, just here to read the source for possible tweaks after trying it)

**Comment by powlo** [comment]
I've also seen 403 Forbidden from MetOffice. [It looks like they had an outage about the time you reported this issue.](https://groups.google.com/forum/#!topic/metoffice-datapoint/Ph5ITq7-6VM) Closing for now, but might try to think of a better way to indicate duff forecasts.

**Comment by powlo** [comment]
For what it's worth I think this is an api issue. There's a limit to the number of free api requests that can be made with the key bundled in the code, so I strongly recommend every user signs up for an api key.

Create an account here:

https://register.metoffice.gov.uk/WaveRegistrationClient/public/newaccount.do?service=datapoint

Once signed up, your MetOffice Datapoint API key can be found on this page.

https://register.metoffice.gov.uk/MyAccountClient/account/view

**Comment by ehuggett** [comment]
I don't suppose there is a way to access the API that would limit per source IP addresses (limited to single digit requests per hour or something)

Are these the limits http://www.metoffice.gov.uk/about-us/legal/fair-usage ?

    You may make no more than 5000 data requests per day; and
    You may make no more than 100 data requests per minute.

(These limits would apply over all Kodi users with the plugin)

***potentially important***: The next paragraph states you agree to allow the met office to "Contact you to discuss how you might reduce your data usage" or "Invoice you for a Paid Data Plan." (£1500 pa!) if you exceed them. I would like to think its not enforceable as its 'hidden' in the TOS (and that they would not even attempt to enforce it unreasonably ie in response to service abuse might be reasonable) but i just want to make sure you aware of this potential liability (to whomever registered the API key currently in use)

I've never knowingly spoken to anyone working at the met office, how unlikely is it that they would agree to lift these limits without charge? (perhaps they have a few kodi users 😄) Even if they would consider it, I suspect putting the api key on github (potentially allowing anyone to use it) may be an issue for them.

I had a quick look for the polling interval currently used, but didn't find it. Assuming 1 hour and everyone leaves kodi running 24/7, a single free api key limits the plugin to (5000 / 24 = ) 208 users as long as no more than half of them try to update in the same minute. Perhaps a little randomisation of the polling interval would help if its currently done on the on the hour every hour to (help) avoid hitting 100 requests in a minute?

**Comment by powlo** [comment]
I'm not sure how often kodi calls the weather script, I can't find any documentation. But there is a cache in place to limit over-requesting. The cache age is defined by the data returned. Eg, Met Office says "this forecast is true for the next two hours."

Randomised polling wouldn't work because we should fetch the data exactly when the user requests it. Data isn't fetched on the hour, but as and when. (User accesses weather page, and cache is invalid).

I could take the API key out, but I was trying to lower barriers to entry. Especially as kodi has no easy way to let a user register with MetOffice Datapoint, and/or tell them that they need to. Let's see how it goes.

**Comment by ehuggett** [comment]
I agree directly randomising/delaying the polling is not suitable when the user has made the request themselves and the cache is empty, especially not as they would have to be made to wait minutes for the delay to have any effect, but those events are going to be somewhat random anyway and so are less likely to collide.

If there is any chance (a lot of) clients could end up with the same cache expiry times (I was under the impression some skins displayed weather data in the title bar/etc? they could be aligned to the hour) adding (or subtracting) a random delay to the cache expiry time would have the same effect (but there would be no delay before fetching the new data when the cache expires).

Having to register for an API key and potentially trying to enter it with a infrared remote control would indeed be awful 😨 I'm not even sure if I will register (although that's mainly down to "it currently works" and the data-feed only containing 3-hourly forecasts unlike the 1 hour forecasts on their website), so the default key is very useful for me but at the same time it would be very unreasonable to criticise or complain if you had chosen to remove it.
