### ISSUE TITLE
Metoffice rejecting python-2.7

### ISSUE THREAD

**Issue by badfish** [powlo/weather.metoffice#5]
I'm getting error 403 responses from the metoffice site.
Testing with 'wget' shows that they respond with 403 if the htp User-Agent is 'Python-urllib-2.7' but anything else (even 'Wget/1.18') works OK.
I've worked around this by patching urlcache.py: change
  response = urllib2.urlopen(url)
to
  opener = urllib2.build_opener()
   opener.addheaders = [('User-Agent', 'Mozilla/5.0')]
   response = opener.open(url)
  opener.close()
Not a python expert, so not sure if this is correct.

**Comment by powlo** [comment]
Nice improvement! Your solution works fine, but it looks like there's a slightly easier way to do this, which involves just making a request object and passing the extra header:

    req = urllib2.Request(url, None, {'User-Agent' : 'Mozilla/5.0'})
    response = urllib2.urlopen(req)

Merged and in the next release!
